FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


FROM node:20-alpine

WORKDIR /app

ENV PORT=4000
ENV HOST=0.0.0.0

COPY --from=build /app/.output ./.output
COPY package*.json ./

RUN npm install --production

EXPOSE 4000

CMD ["node", ".output/server/index.mjs"]
