services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    env_file:
      - ./frontend/.env
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4500

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    env_file:
      - ./backend/.env.production
    expose:
      - "4500"
    depends_on:
      - db
    command: npm run start
