services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    env_file:
      - ./backend/.env.production
    expose:
      - "4500"
    command: npm run start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    env_file:
      - ./frontend/.env
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4500
