export const Tokens = {
  Database: Symbol("Database"),
  UserDataSource: Symbol("UserDataSource"),
  SubmissionDataSource: Symbol("SubmissionDataSource"),
  ServerConfig: Symbol("ServerConfig"),
  PassportConfig: Symbol("PassportConfig"),
  JwtSecret: Symbol("JwtSecret"),
  AuthService: Symbol("AuthService"),
  JwtService: Symbol("JwtService"),
  UserRepository: Symbol("UserRepository"),
  PasswordService: Symbol("PasswordService"),
  SubmissionService: Symbol("SubmissionService"),
  EmailService: Symbol("EmailService"),
  StorageService: Symbol("StorageService"),
  LoginController: Symbol("LoginController"),
  RegisterController: Symbol("RegisterController"),
  PasswordResetController: Symbol("PasswordResetController"),
  SubmissionController: Symbol("SubmissionController"),
} as const;
